"""Continuous command transitions; same state and policy throughout, no resets."""
import os
os.environ['ORT_DISABLE_TELEMETRY']='1';os.environ['OPENBLAS_NUM_THREADS']='1'
import argparse,json,hashlib,concurrent.futures,multiprocessing as mp
from pathlib import Path
import numpy as np,onnxruntime as ort
from env import Env,GAITS
SEQUENCE=['stand','forward_slow','forward','stand','backward','stand','left','right','stand','turn_left','turn_right','stand'];SEGMENT=5.;_CACHE={}
def run_one(task):
 scene,policy,seed,record,out=task;key=(scene,policy)
 if key not in _CACHE:
  e=Env(scene,seed,len(SEQUENCE)*SEGMENT);opt=ort.SessionOptions();opt.intra_op_num_threads=1;opt.inter_op_num_threads=1;s=ort.InferenceSession(policy,sess_options=opt,providers=['CPUExecutionProvider']);_CACHE[key]=(e,s)
 e,s=_CACHE[key];e.rng=np.random.default_rng(seed);e.m.dof_frictionloss[e.vidx]=0.;e.m.dof_damping[e.vidx]=0.;ob=e.reset(GAITS[SEQUENCE[0]]);parts=[];fallen=False;unsafe=False
 for i,name in enumerate(SEQUENCE):
  previous=e.command.copy();target=np.array(GAITS[name]);start=e.d.qpos[:3].copy();start_yaw=e.yaw_unwrapped;start_row=len(e.rows)
  for j in range(round(SEGMENT/.02)):
   e.command=previous+(target-previous)*min(1.,(j+1)*.02/.5);ob=e.obs();action=s.run(None,{s.get_inputs()[0].name:ob[None]})[0][0];ob,r,done,info=e.step(action,record=record)
   if done and (info.get('fall') or info.get('unsafe_self_contact')):fallen=bool(info.get('fall'));unsafe=bool(info.get('unsafe_self_contact'));break
  rr=e.rows[start_row:];settled=rr[min(50,len(rr)//3):];parts.append({'gait':name,'fall':fallen,'unsafe_self_contact':unsafe,'displacement':(e.d.qpos[:3]-start).tolist(),'yaw_change':e.yaw_unwrapped-start_yaw,'mean_velocity':[float(np.mean([r[k]for r in settled]))for k in ['vx','vy','wz']],'max_tilt':max(r['tilt_deg']for r in rr),'seconds':len(rr)*.02})
  if fallen or unsafe:break
 result={'seed':seed,'fall':fallen,'unsafe_self_contact':unsafe,'completed_segments':len(parts),'segments':parts,'simulated_seconds':e.d.time,'compiled_model_sha256':e.base_model_sha256}
 if record:np.savez_compressed(Path(out)/f'transitions_seed{seed}_trace.npz',qpos=e.states,dt=.02)
 return result

def main():
 p=argparse.ArgumentParser();p.add_argument('--scene',required=True);p.add_argument('--policy',required=True);p.add_argument('--out',required=True);p.add_argument('--seeds',type=int,default=5);p.add_argument('--seed-base',type=int,default=5000);p.add_argument('--workers',type=int,default=4);a=p.parse_args();out=Path(a.out);out.mkdir(parents=True,exist_ok=True);tasks=[(str(Path(a.scene).resolve()),str(Path(a.policy).resolve()),a.seed_base+i,i==0,str(out))for i in range(a.seeds)];results=[]
 with concurrent.futures.ProcessPoolExecutor(a.workers,mp_context=mp.get_context('spawn'))as ex:
  for r in ex.map(run_one,tasks):results.append(r);print(json.dumps(r),flush=True)
 report={'results':results,'sequence':SEQUENCE,'segment_seconds':SEGMENT,'command_ramp_seconds':.5,'policy_sha256':hashlib.sha256(Path(a.policy).read_bytes()).hexdigest(),'scene_sha256':hashlib.sha256(Path(a.scene).read_bytes()).hexdigest(),'code_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),'notes':'One free-running rollout per seed; no pose resets at command switches; command schedule is explicit, motion generated by the learned policy through full MuJoCo/BAM dynamics'}
 (out/'transitions.json').write_text(json.dumps(report,indent=2))
if __name__=='__main__':main()
