import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import {gunzipSync} from 'node:zlib';import load from '@mujoco/mujoco';import {Physics} from '../src/physics.js';import * as ort from 'onnxruntime-web/wasm';
const refRoot=process.argv[2]||'reference';
const config=JSON.parse(await readFile('dist/model/config.json')),ref=JSON.parse(await readFile(refRoot+'/trajectory_reference.json')),metadata=JSON.parse(await readFile(refRoot+'/screen_compiled_metadata.json'));const mj=await load();const bytes=gunzipSync(Buffer.concat(await Promise.all(['part1','part2','part3','part4'].map(part=>readFile('dist/model/model.mjb.gz.'+part)))));mj.FS.writeFile('/model.mjb',bytes);const vfs=new mj.MjVFS(),model=mj.MjModel.from_binary_path('/model.mjb',vfs);vfs.delete();mj.FS.unlink('/model.mjb');
const arrayChecks=[];for(const key of ['body_mass','body_inertia','body_ipos','body_iquat','jnt_range','jnt_axis','jnt_pos','dof_armature','dof_solref','dof_solimp','actuator_gainprm','actuator_biasprm','actuator_forcerange','actuator_gear','actuator_trnid','geom_type','geom_contype','geom_conaffinity','geom_friction','geom_solref','geom_solimp','geom_pos','geom_quat','geom_size','pair_geom1','pair_geom2','pair_dim','pair_friction','pair_solref','pair_solimp','pair_margin','pair_gap','mesh_vert','mesh_face','mesh_pos','mesh_quat','sensor_type','sensor_adr']){const a=model[key],expected=metadata.arrays[key];if(!a||!expected){arrayChecks.push({key,skipped:true});continue;}const hash=createHash('sha256').update(Buffer.from(a.buffer,a.byteOffset,a.byteLength)).digest('hex');arrayChecks.push({key,match:hash===expected.sha256});}
const p=new Physics(mj,model,config),max={};function compare(name,a,b){if(a.length!==b.length)throw new Error(name+' length differs');const e=Math.max(0,...Array.from(a,(x,i)=>Math.abs(x-b[i])));max[name]=Math.max(max[name]??0,e);return e;}
for(const key of ['qpos','qvel','ctrl','qfrc_actuator','qfrc_bias','qfrc_constraint'])compare('initial_'+key,p.data[key],ref.initial[key]);compare('initial_obs',p.observation(ref.command),ref.initial.obs);
console.time('open-loop');for(const frame of ref.frames){compare('obs',p.observation(ref.command),frame.obs_before);p.applyAction(frame.action);compare('target',p.target,frame.q_target);for(let k=0;k<4;k++){const s=frame.substeps[k];for(const key of ['qpos','qvel','ctrl','qfrc_actuator','qfrc_bias','qfrc_constraint'])compare('pre_'+key,p.data[key],s.before[key]);p.bamUpdate();compare('ctrl',p.data.ctrl,s.ctrl_after_update);compare('friction',p.model.dof_frictionloss,s.frictionloss_after_update);compare('damping',p.model.dof_damping,s.damping_after_update);mj.mj_step(model,p.data);}p.finishStep(frame.action);for(const key of ['qpos','qvel','ctrl','qfrc_actuator','qfrc_bias','qfrc_constraint'])compare('post_'+key,p.data[key],frame.after[key]);}
console.timeEnd('open-loop');console.log('Open loop maximum errors:',max);console.log('Array mismatches',arrayChecks.filter(x=>!x.match));
ort.env.wasm.numThreads=1;const session=await ort.InferenceSession.create(new Uint8Array(await readFile('dist/model/policy.onnx')),{executionProviders:['wasm']});let onnxMax=0;for(const frame of ref.frames){const output=await session.run({obs:new ort.Tensor('float32',Float32Array.from(frame.obs_before),[1,39])});onnxMax=Math.max(onnxMax,...Array.from(output.actions.data,(x,i)=>Math.abs(x-frame.action[i])));}console.log('ONNX wasm/native max',onnxMax);
const report={mujoco_native_version:'3.10.0',mujoco_wasm_version:mj.mj_versionString(),onnx_native_version:'1.30.0',onnx_web_version:'1.30.0',model_counts:config.counts,compiled_array_checks:arrayChecks,open_loop_controls:ref.frames.length,open_loop_substeps:ref.frames.length*4,open_loop_seconds:ref.frames.length*.02,max_errors:max,onnx_max_action_error:onnxMax,pass:arrayChecks.every(x=>x.match)&&max.post_qpos<1e-7&&max.post_qvel<1e-6&&onnxMax<1e-5};await mkdir('test-results',{recursive:true});await writeFile('test-results/parity.json',JSON.stringify(report,null,2));if(!report.pass)process.exitCode=1;
