import {createRequire} from 'node:module';
import {writeFile,copyFile} from 'node:fs/promises';
const lucide=createRequire(import.meta.url)('lucide');
const names=['Play','Pause','RotateCcw','Undo2','Redo2','Focus','LocateFixed','Square','Info','X','ChevronUp','ChevronDown','ChevronLeft','ChevronRight','Timer','Gauge','MoveUpRight','Activity'];
const render=([tag,attrs,children=[]])=>`<${tag} ${Object.entries(attrs).map(([k,v])=>`${k}="${v}"`).join(' ')}>${children.map(render).join('')}</${tag}>`;
const icons=Object.fromEntries(names.map(name=>{const [tag,attrs,children]=lucide[name];return[name,render([tag,{...attrs,'aria-hidden':'true',focusable:'false','stroke-width':1.8},children])]}));
await writeFile('src/icons.js',`// Selected Lucide 0.468.0 icons, ISC license. Generated by scripts/generate-icons.mjs.\nconst icons=${JSON.stringify(icons)};\nexport function setIcon(element,name){element.innerHTML=icons[name]||'';}\nexport function mountIcons(root=document){for(const el of root.querySelectorAll('[data-icon]'))setIcon(el,el.dataset.icon);}\n`);
await copyFile('node_modules/lucide/LICENSE','src/licenses/Lucide-LICENSE.txt');
