import {Viewer} from './viewer.js?v=pages-1';
import {GAITS,LABELS,snapJoystick} from './control.js';
import {mountIcons,setIcon} from './icons.js';
const $=id=>document.getElementById(id);
let viewer,worker,ready=false,paused=true,requestedPaused=true,mode='stand',slow=true,point=null,keys=new Set(),activeTurn=null,faulted=false;
const controls=['pause','reset','stand','slow','normal','turn-left','turn-right'];
mountIcons();
function send(type,extra={}){worker?.postMessage({type,...extra});}
function setMode(value){if(!ready||paused||faulted)value='stand';mode=value;$('command').textContent=LABELS[value];const cmd=GAITS[value];$('command-value').textContent=cmd[2]?`${cmd[2].toFixed(3)} rad/s`:`${(cmd[0]||cmd[1]).toFixed(3)} m/s`;send('command',{mode});}
function clearPointer(){const previous=point,turn=activeTurn;point=null;activeTurn=null;$('joystick').classList.remove('active');$('stick').style.transform='';for(const id of['turn-left','turn-right'])$(id).classList.remove('active');if(previous&&$('joystick').hasPointerCapture?.(previous.id))$('joystick').releasePointerCapture(previous.id);if(turn&&$(turn.id).hasPointerCapture?.(turn.pointerId))$(turn.id).releasePointerCapture(turn.pointerId);}
function clearInput(){keys.clear();clearPointer();setMode('stand');}
function updatePaused(value){const changed=paused!==value;paused=value;const label=value?'開始':'一時停止';if(changed||!$('pause').dataset.initialized){setIcon($('pause').firstElementChild,value?'Play':'Pause');$('pause').dataset.initialized='true';$('pause').setAttribute('aria-label',label);$('pause').title=label;$('pause').dataset.tip=label;}$('runtime-label').textContent=faulted?'停止':value?'一時停止':'実行中';$('command').hidden=value;document.body.classList.toggle('ready',!value);$('joystick').setAttribute('aria-disabled',String(!ready||value));if(value&&changed)clearInput();}
function showError(message){ready=false;controls.forEach(id=>$(id).disabled=true);$('joystick').setAttribute('aria-disabled','true');$('loading-detail').textContent=message;$('loading').classList.add('fatal');$('runtime-label').textContent='エラー';$('alert').textContent=message;$('alert').hidden=false;}
function modeFromKeys(){if(keys.has('q'))return'turn_left';if(keys.has('e'))return'turn_right';if(keys.has('w')||keys.has('arrowup'))return slow?'forward_slow':'forward';if(keys.has('s')||keys.has('arrowdown'))return'backward';if(keys.has('a')||keys.has('arrowleft'))return'left';if(keys.has('d')||keys.has('arrowright'))return'right';return'stand';}
function updateInput(){if(activeTurn)setMode(activeTurn.mode);else if(point){const r=$('joystick').getBoundingClientRect(),x=(point.x-r.left-r.width/2)/(r.width*.37),y=(point.y-r.top-r.height/2)/(r.height*.37),length=Math.hypot(x,y),scale=length>1?1/length:1;$('stick').style.transform=`translate(${x*scale*r.width*.3}px,${y*scale*r.height*.3}px)`;setMode(snapJoystick(x,y,slow));}else setMode(modeFromKeys());}
$('joystick').addEventListener('pointerdown',e=>{if(!ready||paused||faulted||point)return;e.preventDefault();clearInput();$('joystick').setPointerCapture(e.pointerId);point={x:e.clientX,y:e.clientY,id:e.pointerId};$('joystick').classList.add('active');updateInput();});
$('joystick').addEventListener('pointermove',e=>{if(point?.id===e.pointerId){point={x:e.clientX,y:e.clientY,id:e.pointerId};updateInput();}});
for(const event of['pointerup','pointercancel','lostpointercapture'])$('joystick').addEventListener(event,e=>{if(point?.id===e.pointerId){clearPointer();updateInput();}});
for(const[id,value]of[['turn-left','turn_left'],['turn-right','turn_right']]){const el=$(id);el.addEventListener('pointerdown',e=>{if(!ready||paused||faulted)return;e.preventDefault();clearInput();activeTurn={mode:value,id,pointerId:e.pointerId};el.classList.add('active');el.setPointerCapture(e.pointerId);updateInput();});for(const event of['pointerup','pointercancel','lostpointercapture'])el.addEventListener(event,e=>{if(activeTurn?.id===id&&activeTurn.pointerId===e.pointerId){clearPointer();updateInput();}});}
for(const[id,value]of[['slow',true],['normal',false]])$(id).addEventListener('click',()=>{slow=value;for(const[button,selected]of[['slow',slow],['normal',!slow]]){$(button).classList.toggle('selected',selected);$(button).setAttribute('aria-pressed',String(selected));}updateInput();});
const movementKeys=['w','a','s','d','q','e','arrowup','arrowdown','arrowleft','arrowright'];
window.addEventListener('keydown',e=>{if($('details').open||e.ctrlKey||e.metaKey||e.altKey)return;const key=e.key.toLowerCase();if(key===' '){e.preventDefault();clearInput();send('stand');return;}if(movementKeys.includes(key)){e.preventDefault();if(!ready||paused||faulted||(e.repeat&&!keys.has(key)))return;clearPointer();keys.add(key);updateInput();}});
window.addEventListener('keyup',e=>{if(e.key===' '&&!$('details').open)e.preventDefault();if(keys.delete(e.key.toLowerCase()))updateInput();});
$('pause').addEventListener('click',()=>{if(!ready||faulted)return;clearInput();requestedPaused=!requestedPaused;updatePaused(requestedPaused);send(requestedPaused?'pause':'resume');});
$('reset').addEventListener('click',()=>{faulted=false;requestedPaused=true;updatePaused(true);$('pause').disabled=false;clearInput();send('reset');$('alert').hidden=true;});
$('stand').addEventListener('click',()=>{clearInput();send('stand');});
$('camera-home').addEventListener('click',()=>viewer?.home());
$('follow').addEventListener('click',()=>{const enabled=$('follow').getAttribute('aria-checked')!=='true';$('follow').setAttribute('aria-checked',String(enabled));if(viewer)viewer.follow=enabled;});
function inactive(){requestedPaused=true;clearInput();if(ready){send('pause');updatePaused(true);}}
window.addEventListener('blur',inactive);document.addEventListener('visibilitychange',()=>{if(document.hidden)inactive();});window.addEventListener('pagehide',e=>{inactive();if(!e.persisted)worker?.terminate();});
$('details-open').addEventListener('click',()=>{inactive();$('details').showModal();});$('details-close').addEventListener('click',()=>$('details').close());
setInterval(()=>{if(ready&&!paused&&!document.hidden)send('command',{mode});},100);
async function start(){try{if(!('WebAssembly'in window)||!('Worker'in window)||!('DecompressionStream'in window))throw new Error('このブラウザーでは実行できません');viewer=new Viewer($('viewport'));$('loading-detail').textContent='機体を読み込み中';await viewer.load();worker=new Worker(new URL('./sim-worker.js',import.meta.url),{type:'module'});worker.onmessage=e=>{const m=e.data;if(m.type==='progress')$('loading-detail').textContent=m.message;else if(m.type==='ready'){ready=true;controls.forEach(id=>$(id).disabled=false);$('loading').hidden=true;updatePaused(true);}else if(m.type==='state'){viewer.update(m.transforms,m.telemetry);if(m.paused===requestedPaused)updatePaused(m.paused);$('sim-time').innerHTML=m.telemetry.time.toFixed(2)+'<small>s</small>';$('velocity').innerHTML=Math.hypot(m.telemetry.vx,m.telemetry.vy).toFixed(3)+'<small>m/s</small>';$('tilt').innerHTML=m.telemetry.tilt.toFixed(1)+'<small>°</small>';$('speed').innerHTML=m.ratio.toFixed(2)+'<small>×</small>';if(m.paused&&requestedPaused)setMode('stand');}else if(m.type==='fall'){faulted=true;requestedPaused=true;$('pause').disabled=true;$('alert').textContent=m.message;$('alert').hidden=false;updatePaused(true);}else if(m.type==='error'){inactive();showError(m.message);console.error(m.stack||m.message);}};worker.onerror=e=>{inactive();showError(e.message||'計算を開始できませんでした');};send('init');}catch(e){showError(e.message.includes('WebGL')?'WebGLを利用できません。3D対応のブラウザーで開いてください':e.message);console.error(e);}}
start();
