import * as THREE from 'three';
import {configureScreenTexture} from './screen-texture.js';
import {OrbitControls} from './vendor/three/OrbitControls.js';
function typed(blob,entry){if(!entry)return null;const T=entry.dtype.includes('i')?Int32Array:Float32Array;return new T(blob,entry.offset,entry.bytes/4);}
function meshGeometry(blob,info){const v=typed(blob,info.vertices),f=typed(blob,info.faces),n=typed(blob,info.normals),nf=typed(blob,info.face_normals),uv=typed(blob,info.texcoords),uf=typed(blob,info.face_texcoords);const p=new Float32Array(f.length*3),normals=new Float32Array(p.length),tex=uv&&uf?new Float32Array(f.length*2):null;for(let i=0;i<f.length;i++){for(let k=0;k<3;k++){p[3*i+k]=v[3*f[i]+k];normals[3*i+k]=n[3*(nf?.[i]??f[i])+k];}if(tex){tex[2*i]=uv[2*uf[i]];tex[2*i+1]=uv[2*uf[i]+1];}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('normal',new THREE.BufferAttribute(normals,3));if(tex)g.setAttribute('uv',new THREE.BufferAttribute(tex,2));return g;}
export class Viewer{
 constructor(container){this.container=container;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#eff1ee');this.scene.fog=new THREE.Fog('#eff1ee',3,12);this.camera=new THREE.PerspectiveCamera(36,1,.01,40);this.camera.up.set(0,0,1);this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.35;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;container.append(this.renderer.domElement);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.minDistance=.3;this.controls.maxDistance=4;this.controls.maxPolarAngle=Math.PI*.49;this.controls.target.set(0,0,.24);this.home();const hemi=new THREE.HemisphereLight(0xf5fafb,0x687663,2.3);hemi.up.set(0,0,1);hemi.position.set(0,0,2);this.scene.add(hemi);const sun=new THREE.DirectionalLight(0xfffbf5,3);sun.position.set(1,-2,3);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-1;sun.shadow.camera.right=1;sun.shadow.camera.top=1;sun.shadow.camera.bottom=-1;sun.shadow.camera.near=.1;sun.shadow.camera.far=6;sun.shadow.bias=-.0002;sun.shadow.normalBias=.003;this.sun=sun;this.scene.add(sun,sun.target);const floor=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshStandardMaterial({color:0xe6eae3,roughness:.95}));floor.position.z=-.001;floor.receiveShadow=true;this.scene.add(floor);const grid=new THREE.GridHelper(20,200,0xa4b19e,0xc2cdbe);grid.rotateX(Math.PI/2);grid.position.z=.0001;grid.material.transparent=true;grid.material.opacity=.4;this.scene.add(grid);this.geoms=[];this.root=new THREE.Group();this.scene.add(this.root);this.lastPosition=new THREE.Vector3();this.follow=true;this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);this.resize();this.animate=()=>{this.controls.update();this.renderer.render(this.scene,this.camera);this.animation=requestAnimationFrame(this.animate)};this.animate();}
 home(){const t=this.controls.target;const aspect=this.container.clientWidth/Math.max(1,this.container.clientHeight),scale=Math.max(1,.82/aspect);this.camera.position.set(t.x-.58*scale,t.y-.62*scale,t.z+.22*scale);this.controls.update();}
 resize(){const w=this.container.clientWidth,h=this.container.clientHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);}
 async load(){const [meta,response]=await Promise.all([fetch(new URL('./model/visual.json',import.meta.url)).then(r=>r.json()),fetch(new URL('./model/visual.bin.gz',import.meta.url))]);const blob=await new Response(response.body.pipeThrough(new DecompressionStream('gzip'))).arrayBuffer();const geometries=new Map(meta.meshes.map(info=>[info.id,meshGeometry(blob,info)]));const texture=configureScreenTexture(await new THREE.TextureLoader().loadAsync(new URL('./model/screen.png',import.meta.url).href));texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(4,this.renderer.capabilities.getMaxAnisotropy());const materials=new Map();for(const m of meta.materials){const c=new THREE.Color().setRGB(...m.rgba.slice(0,3));const isScreen=m.texture_ids_by_role.includes(0);let material;if(isScreen)material=new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide});else material=new THREE.MeshStandardMaterial({color:c,roughness:.52,metalness:.08,opacity:m.rgba[3],transparent:m.rgba[3]<1});materials.set(m.id,material);}for(const g of meta.geoms){let mesh=null;if(g.type!==0){let geometry;if(g.type===7)geometry=geometries.get(g.dataid);else if(g.type===6)geometry=new THREE.BoxGeometry(...g.size.map(x=>x*2));else if(g.type===2)geometry=new THREE.SphereGeometry(g.size[0],16,12);else if(g.type===5){geometry=new THREE.CylinderGeometry(g.size[0],g.size[0],g.size[1]*2,20);geometry.rotateX(Math.PI/2);}else if(g.type===3){geometry=new THREE.CapsuleGeometry(g.size[0],g.size[1]*2,6,12);geometry.rotateX(Math.PI/2);}else if(g.type===4){geometry=new THREE.SphereGeometry(1,16,12);geometry.scale(...g.size);}if(geometry){const mat=materials.get(g.matid)??new THREE.MeshStandardMaterial({color:new THREE.Color().setRGB(...g.rgba.slice(0,3)),roughness:.6});mesh=new THREE.Mesh(geometry,mat);mesh.castShadow=true;mesh.receiveShadow=true;mesh.matrixAutoUpdate=false;this.root.add(mesh);}}this.geoms.push(mesh);}this.meta=meta;}
 update(transforms,telemetry){if(transforms.length!==this.geoms.length*12)return;const mat=new THREE.Matrix4();for(let i=0;i<this.geoms.length;i++){const mesh=this.geoms[i];if(!mesh)continue;const o=i*12,r=o+3;mat.set(transforms[r],transforms[r+1],transforms[r+2],transforms[o],transforms[r+3],transforms[r+4],transforms[r+5],transforms[o+1],transforms[r+6],transforms[r+7],transforms[r+8],transforms[o+2],0,0,0,1);mesh.matrix.copy(mat);}const pos=new THREE.Vector3(telemetry.x,telemetry.y,0);if(this.follow){const delta=pos.clone().sub(this.lastPosition);this.camera.position.add(delta);this.controls.target.add(delta);}this.lastPosition.copy(pos);this.sun.position.set(pos.x+1,pos.y-2,3);this.sun.target.position.set(pos.x,pos.y,0);}
 dispose(){cancelAnimationFrame(this.animation);this.resizeObserver.disconnect();this.controls.dispose();this.renderer.dispose();}
}
